### ISSUE TITLE
spine gives correct output but cacti itself says "U"

### ISSUE THREAD

**Issue by gadg3ts** [Busindre/ElasticSearch-Cacti#4]
I'm trying out the cacti templates instead of the pain that appears to be marvel/kibana itself but have a small issue.
Running the elasticsearch.sh script manually, gives me results from the elasticsearch nodes/cluster.
Running (the recompiled) spine manually with the specific hostid, also gives me results.
However, allowing cacti itself to run spine, gives me back "output:U" and no data.

examples
09/09/2016 03:59:41 PM - SPINE: Poller[0] Host[93] TH[1] DS[3682] SCRIPT: /bin/bash /usr/share/cacti/scripts/elasticsearch.sh elasticsearch01 cluster, output: active_primary_shards:53 active_shards:106 relocating_shards:0 initializing_shards:0 unassigned_shards:0 delayed_unassigned_shards:0 cluster_red:0 cluster_yellow:0 cluster_green:1 immediate:0 urgent:0 high:0 normal:0 low:0 languid:0

09/09/2016 04:00:10 PM - SPINE: Poller[0] Host[93] TH[1] DS[3683] SCRIPT: /bin/bash /usr/share/cacti/scripts/elasticsearch.sh elasticsearch01 cluster, output: U

any ideas why this would be?
Thanks,
Sean

**Comment by Busindre** [comment]
Hi Sean.

Please check user privileges and owner of the script.
