### ISSUE TITLE
Small problem with quotes

### ISSUE THREAD

**Issue by coozoo** [Busindre/ElasticSearch-Cacti#6]
Hi,

First of all want to thank you about great work.

Found some problem not sure what it is related for (cacti itself or importing or maybe just mine version or maybe some shielding). So just mentioning it here for anyone who will got the same.

Mine cacti version 1.2.2

Problem that graphs for Index not working at all and I don't see any errors just result that data input method "Elasticsearch index" didn't work at all as result no rrds and no graphs :)

Data Collection->Data Input Methods->Elasticsearch index (Edit)
And change "Input String" from:
```/bin/bash <path_cacti>/scripts/elasticsearch.sh <hostname> index "<index_name>"```
to this:
```/bin/bash <path_cacti>/scripts/elasticsearch.sh <hostname> index <index_name>```

Cleared poller cache and it started to work fine. 

Suppose maybe apply some shielding it will work but actually for me without quotes is enough :)

thanks

**Comment by Busindre** [comment]
Perfect, thanks to you for using and contributing =D.

Greetings!
