### ISSUE TITLE
Elasticsearch JVM datasource old_used_in_bytes limited to 100

### ISSUE THREAD

**Issue by coozoo** [Busindre/ElasticSearch-Cacti#7]
hi,
small issue in datasource

![image](https://user-images.githubusercontent.com/25594311/57380981-bd909f80-71b2-11e9-8776-ccb5072d19ab.png)

old_used_in_bytes shows nan
problem that it's equal to 100 and sure old memory in java far more bigger value.

Templates->Data Source->Elasticsearch JVM (Edit)->old_used_in_bytes and change "Maximum Value ("U" for No Maximum)" from 100 to U

It's better to do before creating charts cause rrd you need to update manually or delete them to apply changes

Anyway there is heap chart to estimate old memory size

**Comment by Busindre** [comment]
Hi @coozoo ,

Can you confirm if the change you propose would be here?

https://github.com/Busindre/ElasticSearch-Cacti/blob/master/cacti_host_template_elasticsearch_jvm_cluster_health_status.xml#L2368

```<rrd_maximum>U</rrd_maximum>```

**Comment by coozoo** [comment]
Yes exactly :)

**Comment by Busindre** [comment]
Done, Thank you very much for your collaboration!
